{% set name = "geovista" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf9087fa5b1917c612d0d60cc3a6dbc6e5fa2ce106b3fe294fbdad0d2a2925b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - geovista = geovista.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >=3.9
    - cartopy >=0.20
    - click
    - click-default-group
    - cmocean
    - colorcet
    - netcdf4
    - numpy >=1.21
    - platformdirs
    - pooch
    - pykdtree
    - pyproj >=3.3
    - pyvista >=0.43.1

test:
  imports:
    - geovista
  commands:
    - pip check
    - geovista --help
  requires:
    - pip

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics powered by PyVista.

  description: |
    GeoVista provides a cartographic gateway into the world of PyVista.
    It leverages the power of the GPU through VTK to provide a paradigm
    shift in rendering performance and interactive user experience.
  dev_url: https://github.com/bjlittle/geovista

extra:
  recipe-maintainers:
    - banesullivan
    - bjlittle
    - tkoyama010
