{% set name = "geovista" %}
{% set version = "0.1a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99aa434a7404c237a69715754cf7f6dbc16fa6d9b51f87a842951b0be770f241

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >=3.7
    - cartopy
    - cmocean
    - colorcet
    - pykdtree
    - pyvista
    - pyvistaqt

test:
  imports:
    - geovista 

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics with PyVista
  description: Cartographic rendering and mesh analytics with PyVista
  
extra:
  recipe-maintainers:
    - bjlittle
