{% set name = "geovista" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74391057e882f9dd2684ff623cdbfdb60d2b4978c0d6b1040943415fb3cf1d48

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - geovista = geovista.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >=3.9
    - cartopy >=0.20
    - click
    - click-default-group
    - cmocean
    - colorcet
    - netcdf4
    - numpy >=1.21
    - platformdirs
    - pooch
    - pyproj >=3.3
    - pyvista >=0.38
    - vtk >=9.2.6

test:
  imports:
    - geovista 
  commands:
    - pip check
    - geovista --help
  requires:
    - pip

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics powered by PyVista.
  dev_url: https://github.com/bjlittle/geovista
  
extra:
  recipe-maintainers:
    - bjlittle
