{% set python_min = '3.10' %}
{% set name = "geovista" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15a200887766179b5d4ffacddc2c4247e9499fce79e38e604c59b7e6793190b8

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - geovista = geovista.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - cartopy >=0.22
    - click
    - click-default-group
    - cmocean
    - colorcet
    - lazy_loader
    - netcdf4
    - numpy >=1.24
    - platformdirs
    - pooch
    - pykdtree
    - pyproj >=3.3
    - pyvista >=0.43.1,<0.45
    - vtk <9.4

test:
  imports:
    - geovista
  commands:
    - pip check
    - geovista --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics powered by PyVista.

  description: |
    GeoVista provides a cartographic gateway into the world of PyVista.
    It leverages the power of the GPU through VTK to provide a paradigm
    shift in rendering performance and interactive user experience.
  dev_url: https://github.com/bjlittle/geovista
  doc_url: https://geovista.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - banesullivan
    - bjlittle
    - tkoyama010
