{% set name = "geovista" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eefee85d204cbeeda5216f9e179bfadf90b49cce1f30b4aa01d20b5254697c43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<3.11
    - pip
    - setuptools >=45
    - setuptools-scm >=7
  run:
    - python >=3.8,<3.11
    - cmocean
    - colorcet
    - cartopy >=0.20
    - click
    - click-default-group
    - netcdf4
    - pooch
    - pyproj >=3.3
    - pyvista =0.37.0
    - pyvistaqt
    - vtk =9.2.2

test:
  imports:
    - geovista 

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics powered by PyVista
  description: Cartographic rendering and mesh analytics powered by PyVista
  
extra:
  recipe-maintainers:
    - bjlittle
