{% set name = "geovista" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ce2154fadece5a2b4c847aa335e2b4ff754a255743b222301a820423c238efa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >=3.8
    - cmocean
    - colorcet
    - cartopy >=0.20
    - click
    - click-default-group
    - netcdf4
    - pooch
    - pyproj >=3.3
    - pyvista >=0.38
    - vtk =9.2.2

test:
  imports:
    - geovista 

about:
  home: https://github.com/bjlittle/geovista
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cartographic rendering and mesh analytics powered by PyVista
  description: Cartographic rendering and mesh analytics powered by PyVista
  
extra:
  recipe-maintainers:
    - bjlittle
